FROM php:8.3-cli
RUN apt-get update && apt-get install -y curl git unzip \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean
WORKDIR /app
COPY composer.json composer.lock ./
COPY src/ ./src/
COPY test/ ./test/
RUN composer install
CMD ["vendor/bin/phpunit", "--testdox", "test/QuickSortTest.php"]



